# Generated by Django 6.0.5 on 2026-07-10 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VerificationReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('report_text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='VerificationSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enable_duplicate_check', models.BooleanField(default=True)),
                ('enable_orphan_check', models.BooleanField(default=True)),
                ('enable_invalid_fk_check', models.BooleanField(default=True)),
            ],
        ),
    ]
