# Generated by Django 6.0.5 on 2026-06-29 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_contactmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleryitem',
            name='category',
            field=models.CharField(default='events', max_length=60),
        ),
    ]
