# Generated by Django 6.0.5 on 2026-06-29 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0003_galleryitem_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='code',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='course',
            name='duration',
            field=models.CharField(blank=True, max_length=80),
        ),
    ]
