# Generated by Django 6.0.3 on 2026-07-18 00:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0002_initial'),
        ('users', '0013_alter_studentprofile_aadhaar_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NoteAccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accessed_at', models.DateTimeField(auto_now=True)),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_logs', to='learning.note')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='note_access_logs', to='users.studentprofile')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('student', 'note'), name='unique_access_per_student_note')],
            },
        ),
        migrations.CreateModel(
            name='VideoWatchLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('watched_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_watch_logs', to='users.studentprofile')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watch_logs', to='learning.videolecture')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('student', 'video'), name='unique_watch_per_student_video')],
            },
        ),
    ]
