# Generated by Django 6.0.5 on 2026-07-01 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feeplan',
            name='fee_type',
            field=models.CharField(choices=[('admission', 'Admission Fee'), ('monthly', 'Monthly Fee'), ('annual', 'Annual Fee'), ('exam', 'Exam Fee'), ('transport', 'Transport Fee'), ('other', 'Other Fee')], default='monthly', max_length=30),
        ),
        migrations.AddField(
            model_name='payment',
            name='academic_session',
            field=models.CharField(default='2026-27', max_length=20),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_type',
            field=models.CharField(choices=[('full_annual', 'Full Annual Payment'), ('monthly_installment', 'Monthly Installment'), ('quarterly', 'Quarterly Payment'), ('admission', 'Admission Fee'), ('partial', 'Partial Payment')], default='monthly_installment', max_length=40),
        ),
        migrations.AddField(
            model_name='payment',
            name='receipt_number',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
