# Generated by Django 6.0.5 on 2026-07-01 16:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_feeplan_fee_type_payment_academic_session_and_more'),
        ('users', '0003_user_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='feeplan',
            name='academic_year',
            field=models.CharField(default='2026-27', max_length=20),
        ),
        migrations.AddField(
            model_name='feeplan',
            name='admission_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='feeplan',
            name='computer_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='feeplan',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='feeplan',
            name='exam_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='feeplan',
            name='late_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='feeplan',
            name='library_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='feeplan',
            name='misc_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='feeplan',
            name='scholarship',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='feeplan',
            name='sports_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='feeplan',
            name='transport_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='feeplan',
            name='tuition_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='payment',
            name='collected_by',
            field=models.CharField(default='System Admin', max_length=120),
        ),
        migrations.AddField(
            model_name='payment',
            name='installment_period',
            field=models.CharField(default='Annual', max_length=50),
        ),
        migrations.AlterField(
            model_name='feeplan',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='feeplan',
            name='fee_type',
            field=models.CharField(choices=[('admission', 'Admission Fee'), ('monthly', 'Monthly Fee'), ('annual', 'Annual Fee'), ('exam', 'Exam Fee'), ('transport', 'Transport Fee'), ('other', 'Other Fee')], default='annual', max_length=30),
        ),
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('cash', 'Cash'), ('upi', 'UPI'), ('card', 'Card'), ('bank_transfer', 'Bank Transfer'), ('online', 'Online Payment Gateway'), ('cheque', 'Cheque'), ('dd', 'Demand Draft')], default='online', max_length=20),
        ),
        migrations.CreateModel(
            name='StudentFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('scholarship', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('waived_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('academic_year', models.CharField(default='2026-27', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fee_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_fees', to='finance.feeplan')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_fees', to='users.studentprofile')),
            ],
            options={
                'unique_together': {('student', 'fee_plan', 'academic_year')},
            },
        ),
        migrations.AddField(
            model_name='payment',
            name='student_fee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='finance.studentfee'),
        ),
    ]
