# Generated by Django 6.0.3 on 2026-07-18 01:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_feeplan_academic_year_feeplan_admission_fee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feeplan',
            name='payment_frequency_options',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='feeplan',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='AdditionalFeeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=150)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_mandatory_for_class', models.BooleanField(default=True)),
                ('fee_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_items', to='finance.feeplan')),
            ],
        ),
    ]
