# Generated by Django 6.0.3 on 2026-07-19 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_feeplan_payment_frequency_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='proof_attachment',
            field=models.FileField(blank=True, null=True, upload_to='proofs/'),
        ),
    ]
