# Generated by Django 6.0.5 on 2026-07-01 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_studentprofile_aadhaar_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherprofile',
            name='blood_group',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
