# Generated by Django 6.0.5 on 2026-07-02 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_studentprofile_admission_class_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='blood_group',
            field=models.CharField(blank=True, default='', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='teacherprofile',
            name='blood_group',
            field=models.CharField(blank=True, default='', max_length=10, null=True),
        ),
    ]
