# Generated by Django 6.0.5 on 2026-07-02 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_studentprofile_blood_group_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='admission_class',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='previous_school',
            field=models.CharField(blank=True, default='', max_length=150, null=True),
        ),
    ]
