# Generated by Django 6.0.5 on 2026-07-02 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_studentprofile_admission_class_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='birth_certificate',
            field=models.FileField(blank=True, null=True, upload_to='birth_certs/'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='documents',
            field=models.FileField(blank=True, null=True, upload_to='student_docs/'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='guardian_occupation',
            field=models.CharField(blank=True, default='', max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='is_profile_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='medical_notes',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='nationality',
            field=models.CharField(blank=True, default='Indian', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='religion',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='student_signature',
            field=models.ImageField(blank=True, null=True, upload_to='student_signatures/'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='transport',
            field=models.CharField(blank=True, default='', max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='alternate_phone',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='assigned_class',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='bank_account_no',
            field=models.CharField(blank=True, default='', max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='bank_ifsc_code',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='is_profile_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='pan_number',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='signature',
            field=models.ImageField(blank=True, null=True, upload_to='signatures/'),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='specialization',
            field=models.CharField(blank=True, default='', max_length=150, null=True),
        ),
    ]
