# Generated by Django 6.0.5 on 2026-07-04 03:19

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_studentprofile_birth_certificate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingRegistration',
            fields=[
            ],
            options={
                'verbose_name': 'Pending Registration',
                'verbose_name_plural': 'Pending Registrations',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('users.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
