# Generated by Django 6.0.5 on 2026-07-10 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_pendingregistration'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherprofile',
            name='aadhaar_number',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
    ]
