# Generated by Django 6.0.5 on 2026-07-10 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_user_address_alter_user_bio_alter_user_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='aadhaar_number',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='bus_route',
            field=models.CharField(blank=True, default='', max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='emergency_contact',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='father_name',
            field=models.CharField(blank=True, default='', max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='guardian_name',
            field=models.CharField(blank=True, default='', max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='guardian_phone',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='house',
            field=models.CharField(blank=True, default='', max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='mother_name',
            field=models.CharField(blank=True, default='', max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='teacherprofile',
            name='bio',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='teacherprofile',
            name='department',
            field=models.CharField(blank=True, default='', max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='teacherprofile',
            name='emergency_contact',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='teacherprofile',
            name='qualification',
            field=models.CharField(blank=True, default='', max_length=160, null=True),
        ),
        migrations.AlterField(
            model_name='teacherprofile',
            name='subjects_taught',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
